# fly.toml app configuration file generated for dawn-field-7506 on 2023-05-11T13:19:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dawn-field-7506"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
